#!/usr/bin/php -q
<?PHP
/* Copyright 2025, IkerSaint, Josh Willox
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License version 2,
 * as published by the Free Software Foundation.
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 */
?>
<?
$config_file = "/boot/config/plugins/zfs.master/zfs.master.cfg";
$docroot = "/usr/local/emhttp";
$plugin = "zfs.master";

require_once "$docroot/webGui/include/Wrappers.php";
require_once "$docroot/webGui/include/publish.php";

require_once $docroot."/plugins/".$plugin."/include/ZFSMHelpers.php";
require_once $docroot."/plugins/".$plugin."/backend/ZFSMOperations.php";

$zfsm_cfg = loadConfig(parse_plugin_cfg($plugin, true));
$zfsm_cfg['version'] = parse_ini_file('/etc/unraid-version')['version'];

$zfsm_cfg_timestamp = 0;

if (is_file($config_file) && is_readable($config_file)):
    $zfsm_cfg_timestamp = filemtime("/boot/config/plugins/zfs.master/zfs.master.cfg");
endif;

function loadCacheData() {
    if (!file_exists('/tmp/zfsm_cache.json')):
        return null;
    endif;

    $cache = json_decode(file_get_contents('/tmp/zfsm_cache.json'), true);

    if (!is_array($cache)):
        return null;
    endif;

    $cache['pools'] = isset($cache['pools']) && is_array($cache['pools']) ? $cache['pools'] : array();
    $cache['devices'] = isset($cache['devices']) && is_array($cache['devices']) ? $cache['devices'] : array();
    $cache['datasets'] = isset($cache['datasets']) && is_array($cache['datasets']) ? $cache['datasets'] : array();

    return $cache;
}

function writeCacheData($data) {
    file_put_contents('/tmp/zfsm_cache.json', json_encode($data));
}

function buildEmptyDatasetData($zpool_name, $include_snapshots) {
    $dataset = array(
        'name' => $zpool_name,
        'child' => array(),
        'mountpoint' => ''
    );

    if ($include_snapshots):
        $dataset['snapshots'] = array();
        $dataset['total_snapshots'] = 0;
    endif;

    return $dataset;
}

function getScopedPoolRefreshData($zpool_name, $include_snapshots, $exclusion_pattern, $directory_listing, $ext) {
    $zpool_info = getZFSPool($zpool_name);

    if (!is_array($zpool_info)):
        return null;
    endif;

    if ($include_snapshots):
        $dataset = getZFSPoolDatasetsAndSnapshots($zpool_name, $exclusion_pattern, $ext, $directory_listing);
        $zpool_info['Snapshots'] = $dataset['total_snapshots'];
    else:
        $dataset = getZFSPoolDatasets($zpool_name, $exclusion_pattern, $ext, $directory_listing);
    endif;

    $zpool_info['MountPoint'] = $dataset['mountpoint'];
    $zpool_info['LastRefresh'] = date('Y-m-d H:i:s');

    return array(
        'pool' => $zpool_info,
        'devices' => getZFSPoolDevices($zpool_name),
        'dataset' => $dataset
    );
}

function isPoolAwake($devices) {
    $device_list = explode("\n", $devices);
    foreach ($device_list as $device) {
        $device = trim($device);
        if (empty($device)) continue;

        // check if it's a disk device (starts with /dev/ or just the name)
        // unraid often uses names like 'sdX' or 'nvmeXn1'
        $path = (strpos($device, '/') === false) ? "/dev/$device" : $device;

        // Use hdparm -C to check power status
        $status = shell_exec("hdparm -C " . escapeshellarg($path) . " 2>&1");
        if (strpos($status, "active/idle") !== false) {
            return true;
        }
    }
    return false;
}

function getData($include_snapshots, $exclusion_pattern, $directory_listing, $ext, $awake_only = 0, $force_pool = null) {
    $cache = loadCacheData();

    if ($force_pool !== null):
        $zpool_global = $cache ? $cache['pools'] : array();
        $zpool_devices = $cache ? $cache['devices'] : array();
        $zpool_datasets = $cache ? $cache['datasets'] : array();

        $scoped_data = getScopedPoolRefreshData($force_pool, $include_snapshots, $exclusion_pattern, $directory_listing, $ext);
        if ($scoped_data !== null):
            $cached_pool = isset($zpool_global[$force_pool]) && is_array($zpool_global[$force_pool]) ? $zpool_global[$force_pool] : array();
            $zpool_global[$force_pool] = array_merge($cached_pool, $scoped_data['pool']);
            $zpool_devices[$force_pool] = $scoped_data['devices'];
            $zpool_datasets[$force_pool] = $scoped_data['dataset'];
        endif;
    else:
        $zpool_global = getZFSPools();
        $zpool_devices = array();
        $zpool_datasets = array();

        foreach ($zpool_global as $zpool):
            $zpool_name = $zpool['Pool'];

            $zpool_devices[$zpool_name] = getZFSPoolDevices($zpool_name);

            $should_refresh = true;
            if ($awake_only):
                $should_refresh = isPoolAwake($zpool_devices[$zpool_name]);
            endif;

            if ($should_refresh) {
                if ($include_snapshots):
                    $zpool_datasets[$zpool_name] = getZFSPoolDatasetsAndSnapshots($zpool_name, $exclusion_pattern, $ext, $directory_listing);
                    $zpool_global[$zpool_name]['Snapshots'] = $zpool_datasets[$zpool_name]['total_snapshots'];
                else:
                    $zpool_datasets[$zpool_name] = getZFSPoolDatasets($zpool_name, $exclusion_pattern, $ext, $directory_listing);
                endif;
                $zpool_global[$zpool_name]['MountPoint'] = $zpool_datasets[$zpool_name]['mountpoint'];
                $zpool_global[$zpool_name]['LastRefresh'] = date('Y-m-d H:i:s');
            } else if ($cache && isset($cache['datasets'][$zpool_name]) && isset($cache['pools'][$zpool_name])) {
                $zpool_datasets[$zpool_name] = $cache['datasets'][$zpool_name];
                $zpool_global[$zpool_name] = $cache['pools'][$zpool_name];
                if (isset($cache['devices'][$zpool_name])):
                    $zpool_devices[$zpool_name] = $cache['devices'][$zpool_name];
                endif;
            } else {
                $zpool_datasets[$zpool_name] = buildEmptyDatasetData($zpool_name, $include_snapshots);
            }
        endforeach;
    endif;

    $message = array();
    if ($force_pool !== null) {
        $message['pool'] = $force_pool;
    }
    $message['data'] = array();
    $message['op'] = $include_snapshots ? "getAll" : "getDatasets";
    $message['data']['pools'] = $zpool_global;
    $message['data']['devices'] = $zpool_devices;
    $message['data']['datasets'] = $zpool_datasets;
    $message['data']['timestamp'] = date('Y-m-d H:i:s');

    publish('zfs_master', json_encode($message));

    return $message;
}

function getAllData($exclusion_pattern, $directory_listing, $ext, $awake_only = 0, $force_pool = null) {
    $refresh_message = array('op' => 'start_refresh');
    if ($force_pool !== null) {
        $refresh_message['pool'] = $force_pool;
    }
    publish('zfs_master', json_encode($refresh_message));

    $message = getData(true, $exclusion_pattern, $directory_listing, $ext, $awake_only, $force_pool);
    writeCacheData($message['data']);

    $refresh_message['op'] = 'stop_refresh';
    publish('zfs_master', json_encode($refresh_message));
}

function getDatasetsSnapshots($zpool, $zdatasets, $ext, &$total_snapshots = 0) {
    foreach ($zdatasets as $dataset_name => $zdataset):
        $snapshots = getDatasetSnapshots($zpool, $zdataset['name'], $ext);
        $zdataset['snapshots'] = $snapshots;
        $total_snapshots += count($snapshots);

        if (isset($zdataset['child']) && count($zdataset['child'])):
            $zdataset['child'] = getDatasetsSnapshots($zpool, $zdataset['child'], $ext, $total_snapshots);
        endif;

        $message = array();
        $message['data'] = array();
        $message['op'] = "getSnapshot";
        $message['data']['pool'] = $zpool;
        $message['data']['dataset'] = $zdataset;
        $message['data']['snapshots'] = $snapshots;

        publish('zfs_master', json_encode($message));

        $zdatasets[$dataset_name] = $zdataset;
    endforeach;

    return $zdatasets;
}

function getLazyLoadData($exclusion_pattern, $directory_listing, $ext, $awake_only = 0, $force_pool = null) {
    $refresh_message = array('op' => 'start_refresh');
    if ($force_pool !== null) {
        $refresh_message['pool'] = $force_pool;
    }
    publish('zfs_master', json_encode($refresh_message));

    $message = getData(false, $exclusion_pattern, $directory_listing, $ext, $awake_only, $force_pool);

    foreach ($message['data']['datasets'] as $zpool_name => &$zpool):
        if ($force_pool !== null && $zpool_name !== $force_pool):
            continue;
        endif;

        if (isset($zpool['child']) && count($zpool['child'])) {
            $total_snapshots = 0;
            $zpool['child'] = getDatasetsSnapshots($zpool_name, $zpool['child'], $ext, $total_snapshots);
            if (isset($message['data']['pools'][$zpool_name])):
                $message['data']['pools'][$zpool_name]['Snapshots'] = $total_snapshots;
            endif;
        }
    endforeach;

    writeCacheData($message['data']);

    $refresh_message['op'] = 'stop_refresh';
    publish('zfs_master', json_encode($refresh_message));
}

function notifyConfigUpdate($config) {
    $message = array();
    $message['data'] = $config;
    $message['op'] = "updateConfig";

    publish('zfs_master', json_encode($message));
}

$sleep_time = 0.0;
$iters = 0;

while (true) {
    if ($iters > 15):
        if (is_file($config_file) && is_readable($config_file)):
            if (filemtime($config_file) != $zfsm_cfg_timestamp):
                $zfsm_cfg = loadConfig(parse_plugin_cfg($plugin, true));
                $zfsm_cfg['version'] = parse_ini_file('/etc/unraid-version')['version'];
                $zfsm_cfg_timestamp = filemtime("/boot/config/plugins/zfs.master/zfs.master.cfg");

                notifyConfigUpdate($zfsm_cfg);
            endif;
        endif;

        $iters = 0;
    endif;


    $force_pool = null;
    if (file_exists('/tmp/zfsm_reload_pool')):
        $force_pool = trim(file_get_contents('/tmp/zfsm_reload_pool'));
        unlink('/tmp/zfsm_reload_pool');
    endif;

    if ($zfsm_cfg['refresh_interval'] == 0 && (file_exists('/tmp/zfsm_reload') == true || $force_pool)):
        if (file_exists('/tmp/zfsm_reload')) unlink('/tmp/zfsm_reload');

        if ($zfsm_cfg['lazy_load'] == "0"):
            getAllData($zfsm_cfg['dataset_exclusion'], $zfsm_cfg['directory_listing'], $zfsm_cfg['znapzend_data'], $zfsm_cfg['refresh_awake_only'], $force_pool);
        else:
            getLazyLoadData($zfsm_cfg['dataset_exclusion'], $zfsm_cfg['directory_listing'], $zfsm_cfg['znapzend_data'], $zfsm_cfg['refresh_awake_only'], $force_pool);
        endif;

    elseif (($zfsm_cfg['refresh_interval'] > 0 && $zfsm_cfg['refresh_interval'] <= $sleep_time) || file_exists('/tmp/zfsm_reload') == true || $force_pool):
        if (file_exists('/tmp/zfsm_reload')):
            unlink('/tmp/zfsm_reload');
        endif;

        if ($zfsm_cfg['lazy_load'] == "0"):
            getAllData($zfsm_cfg['dataset_exclusion'], $zfsm_cfg['directory_listing'], $zfsm_cfg['znapzend_data'], $zfsm_cfg['refresh_awake_only'], $force_pool);
        else:
            getLazyLoadData($zfsm_cfg['dataset_exclusion'], $zfsm_cfg['directory_listing'], $zfsm_cfg['znapzend_data'], $zfsm_cfg['refresh_awake_only'], $force_pool);
        endif;

        $sleep_time = 0.0;
    endif;

    usleep(150000); 
    $sleep_time += 0.15;
    $iters += 1;
}
?>